name: android-apk-debug
on:
  workflow_dispatch:

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # This installs the specific NDK version requested by the error
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;23.1.7779620"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build command without proxy interference
      - name: Build debug APK
        run: ./gradlew assembleDebug --no-daemon -Dhttp.proxyHost -Dhttp.proxyPort -Dhttps.proxyHost -Dhttps.proxyPort

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: rfidtools-debug-apk
          path: "**/build/outputs/apk/debug/*.apk"
