name: android-apk-debug
on:
  workflow_dispatch:

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install Android Components
        run: |
          echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install \
            "ndk;23.1.7779620" \
            "cmake;3.10.2.4988404" \
            "build-tools;30.0.3"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        # 1. We skip 'downloadBootstraps' because Bintray is dead.
        # 2. We force-clear all proxy variables.
        run: |
          export http_proxy=""
          export https_proxy=""
          export HTTP_PROXY=""
          export HTTPS_PROXY=""
          ./gradlew assembleDebug --no-daemon \
            -x downloadBootstraps \
            -Dhttp.proxyHost="" -Dhttp.proxyPort="" \
            -Dhttps.proxyHost="" -Dhttps.proxyPort=""

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: rfidtools-debug-apk
          path: "**/build/outputs/apk/debug/*.apk"
